export const KeyUtils = {
  keys: {
    user: 'user',
    verificationCompleted: 'verificationCompleted',
    bearerToken: 'bearerToken',
    theme: 'theme',
  },
  screens: {
    Login: 'Login',
    SignUp: 'Signup',
    Splash: 'Splash',
    Verify: 'Verify',
    DrawerNavigator: 'DrawerNavigator',
    HomeTopTabs: 'HomeTopTabs',
    BottomTabs: 'BottomTabs',
    MarketPlaceNavigator: 'MarketPlaceNavigator',
    HomeNav: 'HomeNav',
    ShowPost: 'ShowPost',
    AddPost: 'AddPost',
    SearchCommunity: 'SearchCommunity',
    AddImage: 'AddImage',
    Feed: 'Feed',
    Marketplace: 'Marketplace',
    ProductDetails: 'ProductDetails',
    CreatePost: 'CreatePost',
    Community: 'Community',
    User: 'User',
    MessagingStack: 'Messaging',
    UserPosts: 'UserPosts',
    ProfileScreen: 'profileScreen',
    AddDescription: 'AddDescription',
    Settings: 'Settings',
    GeneralInformation: 'GeneralInformation',
    PasswordAndSecurity: 'PasswordAndSecurity',
    CreateCommunity: 'CreateCommunity',
    CommunityDetails: 'CommunityDetails',
    PaymentModal: 'PaymentModal',
    PaymentScreen: 'PaymentScreen',
    Appearance: 'Appearance',
    Chats : "Chats",
    Messages : "Messages",
    UserTestimonials : "UserTestimonial"
  },
}
